version: '3.9'

services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret_pw
  
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

  populate_db:
    build: './data'
    profiles:
      - setup

    depends_on:
      mysql:  
        condition: service_healthy
  
  
  backend_test:
    profiles:
      - testing
    build: 
      context: './backend'
      dockerfile: 'Dockerfile.test'
    environment:
      - NODE_ENV=TEST
      - HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=secret_pw
    depends_on:
      populate_db:   
        condition: service_completed_successfully
    

  backend:
    build: './backend'
    environment:
      - NODE_ENV=DEVELOPMENT
      - HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=secret_pw
    ports:
      - 3000:3000
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      populate_db:  
        condition: service_completed_successfully

volumes:
  mysql-data: